Item_Boiled_01: "Hard-Boiled Egg",
    Item_ChilledFish_01: "冰冻生命鲈鱼",
    Item_ChilledFish_02: "冰冻生命三文鱼",
    Item_ChilledFish_03: "冰冻鳟鱼",
    Item_ChilledFish_04: "冰冻鲤鱼",
    Item_ChilledFish_05: "冰冻鲷鱼",
    Item_ChilledFish_06: "冰冻生命鲈鱼",
    Item_ChilledFish_07: "冰冻螃蟹",
    Item_ChilledFish_08: "冰冻田螺",
    Item_ChilledFish_09: "冰冻生命海螺",
    Item_RoastFish_01: "烤鲈鱼",
    Item_RoastFish_02: "烤生命鲈鱼",
    Item_RoastFish_03: "烤鳟鱼",
    Item_RoastFish_04: "烤生命三文鱼",
    Item_RoastFish_07: "烤鲤鱼",
    Item_RoastFish_09: "烤鲷鱼",
    Item_RoastFish_11: "烤生命海螺",
    Item_RoastFish_13: "烤潜行田螺",
    Item_RoastFish_15: "烤螃蟹",
    Item_Roast_01: "烤兽肉",
    Item_Roast_02: "烤禽肉",
    Item_Roast_03: "烤苹果",
    Item_Roast_04: "烤精力蘑菇",
    Item_Roast_05: "烤生命松露",
    Item_Roast_06: "烤海拉鲁蘑菇",
    Item_Roast_07: "烤草莓",
    Item_Roast_08: "烤酥麻水果",
    Item_Roast_09: "烤生命榴莲",
    Item_Roast_10: "烤椰子",
    Item_Roast_11: "烤大剑香蕉",
    Item_Roast_12: "烤冰冷蜜瓜",
    Item_Roast_13: "烤暖暖草果",
    Item_Roast_15: "烤铠甲南瓜",
    Item_Roast_16: "Roasted Lotus Seed",
    Item_Roast_18: "烤小萝卜",
    Item_Roast_19: "烤大萝卜",
    Item_Roast_24: "烤速速胡萝卜",
    Item_Roast_27: "烤大剑草",
    Item_Roast_28: "烤铠甲草",
    Item_Roast_31: "烤冰冷蘑菇",
    Item_Roast_32: "烤暖暖蘑菇",
    Item_Roast_33: "烤酥麻蘑菇",
    Item_Roast_36: "烤速速蘑菇",
    Item_Roast_37: "烤大剑蘑菇",
    Item_Roast_38: "烤铠甲蘑菇",
    Item_Roast_39: "烤潜行蘑菇",
    Item_Roast_40: "烤高级兽肉",
    Item_Roast_41: "烤高级禽肉",
    Item_Roast_45: "烤顶级兽肉",
    Item_Roast_46: "烤顶级禽肉",
    Item_Roast_48: "烤橡子",
    Item_Roast_49: "Toasted Big Heart Truffle",
    Item_Roast_50: "烤毅力胡萝卜",
    Item_Roast_51: "烤蛋",
    Item_Roast_52: "烤树果",
    Item_Roast_53: "烤毅力蘑菇",
    Item_Chilled_01: "冰冻兽肉",
    Item_Chilled_02: "高级冰冻兽肉",
    Item_Chilled_03: "顶级冰冻兽肉",
    Item_Chilled_04: "冰冻禽肉",
    Item_Chilled_05: "高级冰冻禽肉",
    Item_Chilled_06: "顶级冰冻禽肉",
    Item_Cook_A_01: "烤蘑菇串",
    Item_Cook_A_02: "蒸蘑菇",
    Item_Cook_A_03: "烤椰子",
    Item_Cook_A_04: "蒸魚",
    Item_Cook_A_05: "蒸肉",
    Item_Cook_A_07: "水果拌蘑菇",
    Item_Cook_A_08: "烤魚蘑菇串",
    Item_Cook_A_09: "烤肉蘑菇串",
    Item_Cook_A_10: "煎蛋卷",
    Item_Cook_A_11: "甘露燉蘑菇",
    Item_Cook_A_12: "Glazed Meat",
    Item_Cook_A_13: "甘露燉魚",
    Item_Cook_A_14: "甘露燉蔬菜",
    Item_Cook_B_01: "炒野菜",
    Item_Cook_B_02: "Simmered Fruits",
    Item_Cook_B_05: "烤魚",
    Item_Cook_B_06: "烤肉串",
    Item_Cook_B_11: "大份炒野菜",
    Item_Cook_B_12: "Copious Simmered Fruits",
    Item_Cook_B_13: "大份烤蘑菇串",
    Item_Cook_B_15: "Copious Seafood Skewers",
    Item_Cook_B_16: "大份烤肉串",
    Item_Cook_B_17: "海陸煎烤 - tr",
    Item_Cook_B_18: "高級海陸煎烤 - tr",
    Item_Cook_B_19: "頂級海陸煎烤 - tr",
    Item_Cook_B_20: "Meat-Stuffed Pumpkin",
    Item_Cook_B_21: "Sautéed Peppers",
    Item_Cook_B_22: "Sautéed Nuts",
    Item_Cook_B_23: "Seafood Skewers",
    Item_Cook_C_16: "精灵回力水",
    Item_Cook_C_17: "Elixir",
    Item_Cook_D_01: "鹽烤蘑菇 - tr",
    Item_Cook_D_02: "鹽烤野菜 - tr",
    Item_Cook_D_03: "鹽烤魚 - tr",
    Item_Cook_D_04: "岩鹽烤肉 - tr",
    Item_Cook_D_05: "高級岩鹽烤肉 - tr",
    Item_Cook_D_06: "頂級岩鹽烤肉",
    Item_Cook_D_07: "Pepper Steak",
    Item_Cook_D_08: "香辣煎魚 - tr",
    Item_Cook_D_09: "岩鹽烤蟹 - tr",
    Item_Cook_D_10: "炒螃蟹 - tr",
    Item_Cook_E_01: "禽肉菜飯 - tr",
    Item_Cook_E_02: "高級禽肉菜飯 - tr",
    Item_Cook_E_03: "頂級禽肉菜飯 - tr",
    Item_Cook_E_04: "煎蛋飯 - tr",
    Item_Cook_F_01: "鮮肉牛奶湯 - tr",
    Item_Cook_F_02: "海鮮牛奶湯 - tr",
    Item_Cook_F_03: "蔬菜濃湯 - tr",
    Item_Cook_F_04: "心心牛奶湯 - tr",
    Item_Cook_G_02: "海鮮飯糰 - tr",
    Item_Cook_G_03: "野菜飯糰 - tr",
    Item_Cook_G_04: "蘑菇飯糰 - tr",
    Item_Cook_G_05: "獸肉蓋飯 - tr",
    Item_Cook_G_06: "高級獸肉蓋飯 - tr",
    Item_Cook_G_09: "頂級獸肉蓋飯 - tr",
    Item_Cook_G_10: "海鮮炒飯 - tr",
    Item_Cook_G_11: "咖哩菜飯 - tr",
    Item_Cook_G_12: "蘑菇烩饭",
    Item_Cook_G_13: "蔬菜烩饭",
    Item_Cook_G_14: "三文鱼烩饭",
    Item_Cook_G_15: "鮮肉飯糰 - tr",
    Item_Cook_G_16: "蟹肉蛋炒飯 - tr",
    Item_Cook_G_17: "蟹肉烩饭",
    Item_Cook_H_01: "Seafood Meunière",
    Item_Cook_H_02: "Porgy Meunière",
    Item_Cook_H_03: "Salmon Meunière",
    Item_Cook_I_01: "水果派 - tr",
    Item_Cook_I_02: "蘋果派 - tr",
    Item_Cook_I_03: "蛋撻 - tr",
    Item_Cook_I_04: "鮮肉派 - tr",
    Item_Cook_I_05: "胡蘿蔔蛋糕 - tr",
    Item_Cook_I_06: "南瓜蛋糕 - tr",
    Item_Cook_I_07: "奶油蘋果 - tr",
    Item_Cook_I_08: "Honeyed Apple",
    Item_Cook_I_09: "蜂蜜水果 - tr",
    Item_Cook_I_10: "原味可麗餅 - tr",
    Item_Cook_I_11: "草莓可麗餅 - tr",
    Item_Cook_I_12: "堅果蛋糕 - tr",
    Item_Cook_I_13: "炸香蕉 - tr",
    Item_Cook_I_14: "鮮蛋布丁 - tr",
    Item_Cook_I_15: "魚肉派 - tr",
    Item_Cook_I_16: "Honey Candy",
    Item_Cook_I_17: "蜂蜜可麗餅 - tr",
    Item_Cook_J_01: "咖哩飯 - tr",
    Item_Cook_J_02: "蔬菜咖哩飯 - tr",
    Item_Cook_J_03: "Seafood Curry",
    Item_Cook_J_04: "Poultry Curry",
    Item_Cook_J_05: "Prime Poultry Curry",
    Item_Cook_J_06: "Meat Curry",
    Item_Cook_J_07: "Prime Meat Curry",
    Item_Cook_J_08: "Gourmet Poultry Curry",
    Item_Cook_J_09: "Gourmet Meat Curry",
    Item_Cook_K_01: "Meat Stew",
    Item_Cook_K_02: "Prime Meat Stew",
    Item_Cook_K_03: "Pumpkin Stew",
    Item_Cook_K_04: "Clam Chowder",
    Item_Cook_K_05: "Gourmet Meat Stew",
    Item_Cook_K_06: "Cream of Mushroom Soup",
    Item_Cook_K_07: "Cream of Vegetable Soup",
    Item_Cook_K_08: "Carrot Stew",
    Item_Cook_K_09: "Milk",
    Item_Material_05_00: "Milk x0",
    Item_Cook_L_01: "Monster Stew",
    Item_Cook_L_02: "Monster Soup",
    Item_Cook_L_03: "Monster Cake",
    Item_Cook_L_04: "Monster Rice Balls",
    Item_Cook_L_05: "Monster Curry",
    Item_Cook_M_01: "Wheat Bread",
    Item_Cook_N_01: "Seafood Paella",
    Item_Cook_N_02: "Fruitcake",
    Item_Cook_N_03: "Vegetable Omelet",
    Item_Cook_N_04: "Mushroom Omelet",
    Item_Cook_O_01: "Dubious Food",
    Item_Cook_O_02: "Rock-Hard Food",
    Item_Cook_P_01: "Fragrant Mushroom Sauté",
    Item_Cook_P_02: "Herb Sauté",
    Item_Cook_P_03: "Spiced Meat Skewer",
    Item_Cook_P_04: "Prime Spiced Meat Skewer",
    Item_Cook_P_05: "Gourmet Spiced Meat Skewer"