Obj_DungeonClearSeal: "试练通过之证",
    Obj_KorokNuts: "克洛洛的果实",
    PlayerStole2: "滑翔帆",
    Obj_ProofBook: "秘密信封",
    Obj_DRStone_Get: "希卡之石",
    Obj_HeroSoul_Zora: "英杰米法的祈福",
    Obj_HeroSoul_Gerudo: "英杰乌尔波扎的愤怒",
    Obj_HeroSoul_Goron: "英杰达克尔克的守护",
    Obj_HeroSoul_Rito: "英杰力巴尔的勇猛",
    Obj_DLC_HeroSoul_Zora: "英杰米法的祈福 + [DLC v1.4]",
    Obj_DLC_HeroSoul_Gerudo: "英杰乌尔波扎的愤怒 + [DLC v1.4]",
    Obj_DLC_HeroSoul_Goron: "英杰达克尔克的守护 + [DLC v1.4]",
    Obj_DLC_HeroSoul_Rito: "英杰力巴尔的勇猛 + [DLC v1.4]",
    Obj_Maracas: "伯库林的沙球",
    Obj_ProofKorok: "伯库林的果实",
    Obj_ProofSandwormKiller: "拉吉克屠戮者之证",
    Obj_ProofGiantKiller: "西诺克斯屠戮者之证",
    Obj_ProofGolemKiller: "岩石巨人屠戮者之证",
    KeySmall: "Small Key",
    Obj_Armor_115_Head: "雷鸣头盔",
    GameRomHorseReins_00: "旅人缰绳",
    GameRomHorseReins_01: "Traveler's Bridle",
    GameRomHorseReins_02: "王族缰绳",
    GameRomHorseReins_03: "骑士马鞍",
    GameRomHorseReins_04: "怪物缰绳",
    GameRomHorseReins_05: "奢华缰绳",
    GameRomHorseReins_10: "古代缰绳 [DLC v1.4]",
    GameRomHorseSaddle_00: "Stable Saddle",
    GameRomHorseSaddle_01: "旅人马鞍",
    GameRomHorseSaddle_02: "王族马鞍",
    GameRomHorseSaddle_03: "骑士马鞍",
    GameRomHorseSaddle_04: "怪物马鞍",
    GameRomHorseSaddle_05: "奢华马鞍",
    GameRomHorseSaddle_10: "古代马鞍 [DLC v1.4]",
    GameRomHorse00S: "Donkey",
    GameRomHorseNushi: "山神｜貌似没用",
    GameRomHorseEpona: "Epona",
    GameRomHorseBone: "Stalhorse",
    GameRomHorse00L: "Giant Horse",
    GameRomHorseZelda: "Royal White Stallion",
    Obj_WarpDLC: "传送标注器",
    Get_TwnObj_DLC_MemorialPicture_A_01: "英杰们的照片 [DLC v1.4]"